### ISSUE TITLE
Inconsistency of description of when a Query operation can be performed

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/amazon-dynamodb-developer-guide#121]
[API_Query](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html) says:

> The Query operation finds items based on primary key values. You can query any table or secondary index that has a composite primary key (a partition key and a sort key).

Meanwhile, [Primary Key docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey) says:

> DynamoDB supports two different kinds of primary keys:
**Partition key** – A simple primary key, composed of one attribute known as the partition key.
...
**Partition key and sort key** - Referred to as a composite primary key, this type of key is composed of two attributes. The first attribute is the partition key, and the second attribute is the sort key.

But query can be performed on a table or secondary index that doesn't have a composite primary key (i.e., it can be performed on a table / secondary index with a simple primary key.)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
