### ISSUE TITLE
Documentation mismatch on Amazon DynmoDB: How It Works

### ISSUE THREAD

**Issue by shawnkoon** [awsdocs/amazon-dynamodb-developer-guide#126]
#### AWS Doc:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.html

#### GitHub Doc:
https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/HowItWorks.md

#### Problem:
One of the bullets under Topics mismatches from GitHub & Official doc.

```markdown
# GitHub
- Throughput Capacity for Reads and Writes

# AWS Doc
- Read/Write Capacity Mode
```

I don't know if I am missing something but markdown page *Read/Write Capacity Mode* no longer exists, so `Edit on GitHub` link in that page throws a 404 not found.

**Comment by santisra** [comment]
Thanks for your feedback. I'll update the github repo soon to address your concern.

**Comment by shawnkoon** [comment]
Thanks!

**Comment by mouahm** [comment]
mismatch should be resolved now
