### ISSUE TITLE
Incorrect data in the example section of Read Capacity Units and Write Capacity Units

### ISSUE THREAD

**Issue by nagaran1** [awsdocs/amazon-dynamodb-developer-guide#188]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html

As the above document says "One read capacity unit represents one strongly consistent read per second, or two eventually consistent reads per second, for an item up to 4 KB in size. **Transactional read requests** require two read capacity units to perform **one read per second** for items up to **4 KB**."

With respect to above definition, the highlighted line in below screen shot should be "Perform transactional **read** requests of up to **12 KB** per second." Instead of "Perform transactional **read** requests of up to **3 KB** per second."

![image](https://user-images.githubusercontent.com/16425994/58020695-8b722c80-7b26-11e9-89d0-7d0e83d3bd25.png)

**Comment by mouahm** [comment]
Thank you for raising the issue, this has been fixed in the public documentation & will be publishing the changes to github
