### ISSUE TITLE
Wrong translation regarding "Query" and "Scan"

### ISSUE THREAD

**Issue by ytakahashi** [awsdocs/amazon-dynamodb-developer-guide#189]
In [Best Practices for Querying and Scanning Data](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-query-scan.html), it's recommended to use Query instead of Scan.

> For faster response times, design your tables and indexes so that your applications can use Query instead of Scan. 
 
But in [Japanese page](https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/developerguide/bp-query-scan.html), this is translated into following sentence:

> 高速な応答時間を得るには、アプリケーションが Query ではなく Scan を使用できるようにテーブルとインデックスを設計します

Here, "Query" and "Scan" are written in the other way around.

**Comment by NicholasDunham** [comment]
This is now fixed. Thank you!
