### ISSUE TITLE
Node.JS Demo Have wrong Time Analysis. Javascript is Async in nature...

### ISSUE THREAD

**Issue by charlieding** [awsdocs/amazon-dynamodb-developer-guide#2]
The average times reported by the demo Node.JS is wrong. Javascript finishes execution in Asynchronous way.

**Comment by santisra** [comment]
We'll look into this. Thanks

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
