### ISSUE TITLE
Very important part in a doc page is missing

### ISSUE THREAD

**Issue by peske** [awsdocs/amazon-dynamodb-developer-guide#209]
I've just read [JavaScript and DynamoDB](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/GettingStarted.JavaScript.md) doc page. In my opinion, a very important explanation is missing there: **When to use such implementation** (direct access to DynamoDB from client JavaScript). I may be wrong about this, but I think that it's very risky to create public web applications which are directly accessing DynamoDB from JavaScript for a simple reason: a malicious user would be able to emit any queries to the DB, which are either changing the data in a malicious way or returning a data which shouldn't be available for the user, or at very least to create many scans/selects thus causing throttling and costs. If such access is possible, shouldn't be there some note like: "_Use this only in internal apps used by trusted users_", or something like that?

**Comment by NicholasDunham** [comment]
As mentioned further into the tutorial, when using the JavaScript API in production on a website it's always best to authenticate users with Amazon Cognito.
