### ISSUE TITLE
documentation on pagination is inconsistent

### ISSUE THREAD

**Issue by stefangotz** [awsdocs/amazon-dynamodb-developer-guide#210]
`amazon-dynamodb-developer-guide/doc_source/Query.md` initially says: _If LastEvaluatedKey is present in the response and is non-null, you will need to paginate the result set_

However, under _Paginating the Results_, it then goes on to say _If the result contains a LastEvaluatedKey element, proceed to step 2. If there is not a LastEvaluatedKey in the result, then there are no more items to be retrieved_

And most further mentions of `LastEvaluatedKey` no longer say that `LastEvaluatedKey` needs to be both present and non-null, including code samples.

Therefore, as an application developer, I'm now not sure whether I should check `LastEvaluatedKey` to be non-null or not.

To avoid confusion, would it make sense to clarify which of the statements is true and make them all consistent?

**Comment by NicholasDunham** [comment]
Thanks for pointing this out! I've added some clarification, and the change will appear in the public docs shortly.
