### ISSUE TITLE
Misleading info - GetItem events are not put on a stream

### ISSUE THREAD

**Issue by oliver-nettleton-emis** [awsdocs/amazon-dynamodb-developer-guide#211]
There is some misleading information on the page https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices-security-detective.html where it says 

> AWS CloudTrail does not support logging of DynamoDB data-plane operations, such as GetItem and PutItem. So you might want to consider using Amazon DynamoDB Streams as a source for these events occurring in your environment.

This suggests that you can use streams to audit GetItem events but streams will only generate a record for an item that has changed/inserted/deleted.

I believe the reference to GetItem should be removed from the page.

**Comment by NicholasDunham** [comment]
Thanks for noticing this! I've removed the mention of GetItem on that page. The update will appear in the public docs shortly.
