### ISSUE TITLE
AWS Services that work with IAM: Service Linked Role

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-dynamodb-developer-guide#212]
From clicking through the IAM guide here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html, I noticed that this page only talks about Service Roles for DAX and does not mention the new Service role for DynamoDB Replication: AWSServiceRoleForDynamoDBReplication.

Should this page be updated to reflect the AWSServiceRoleForDynamoDBReplication?

**Comment by NicholasDunham** [comment]
I'm not sure which page you're referring to—the page in the IAM User Guide, or a page in the DynamoDB Developer Guide?
