### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by jakobbraun** [awsdocs/amazon-dynamodb-developer-guide#218]
In order to cite the documentation in a paper I am looking for a permalink a specific version of the documentation.
In the url of the PDF is always a latest: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/dynamodb-dg.pdf

Are there also static versions available?

**Comment by NicholasDunham** [comment]
Unfortunately, no, there's no static/versioned option for the developer guide, nor is this an option with our current documentation build process. I'll convey your feedback to the appropriate team, but for now I'll close this issue.
