### ISSUE TITLE
Table scan example cause endless loop

### ISSUE THREAD

**Issue by Artromskiy** [awsdocs/amazon-dynamodb-developer-guide#222]
Using of Async methods to scan table cause endless loop.
![image](https://user-images.githubusercontent.com/47901401/82252926-a43f3900-9958-11ea-99f1-ace67f7fc714.png)
![image](https://user-images.githubusercontent.com/47901401/82253000-cb960600-9958-11ea-9236-c1ac49c4d988.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
