### ISSUE TITLE
Summary page missing for ".NET and DynamoDB"

### ISSUE THREAD

**Issue by sandeepksaini** [awsdocs/amazon-dynamodb-developer-guide#234]
The summary page is missing for ".NET and DynamoDB" module under "Getting Started with the AWS SDKs".

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NET.10.html

![image](https://user-images.githubusercontent.com/25612676/98880865-d16e3d80-24dc-11eb-9470-0b514eab4395.png)

**Comment by 70663594456** [comment]
#235

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
