### ISSUE TITLE
partition keys do need to be have a large number of distinct values relative to the number of items in the table

### ISSUE THREAD

**Issue by pluresideas** [awsdocs/amazon-dynamodb-developer-guide#236]
The following example from the documentation seems to suggest that partition keys do not need to be have a large number of distinct values relative to the number of items in the table:

**"Suppose that the Pets table has a composite primary key consisting of AnimalType (partition key) and Name (sort key)."**

I think using the `Name` as a partition key would be a better, more correct example given the following Amazon recommendation:

**"DynamoDB is optimized for uniform distribution of items across a table's partitions, no matter how many partitions there may be. We recommend that you choose a partition key that can have a large number of distinct values relative to the number of items in the table."**

I suggest that the example is updated to use `Name` as a **partition key** and `AnimalType` as a **sort key** to help developers designing better solutions.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
