### ISSUE TITLE
code samples for aws-sdk-go-v2 is missing

### ISSUE THREAD

**Issue by ghost** [awsdocs/amazon-dynamodb-developer-guide#243]
Code samples for most common DynamoDB operations are missing in both go v2 sdk documentation and DynamoDB Documentation. 
There is no simple and clear listing of all the Golang modules one may need to use the service. I was not aware of github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbattribute module and was trying to reinvent the wheel.
Some guidance on usage of the tag `dynamodbav` could be super helpful.
Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
