### ISSUE TITLE
begin_with filter expression support for a random key alone

### ISSUE THREAD

**Issue by AnweshaSen** [awsdocs/amazon-dynamodb-developer-guide#248]
I have a table structure as :
| id | name | entry_date | exit_date | ... |
where id is the partition key. Now the format for entry_date is : "E MMM dd HH:mm:ss z yyyy" 
I want pairs(<id, entry_date>) for all entry_date >= givenStartDate and entry_date <= givenEndDate  or only id with entry_date = givenStartDate will work.
I have tried scan with >, <, between filters on dynamodb UI, but it's not giving exact result there and same with a java query. But on UI, begins_with filter is working fine if I consider only givenStartDate. But while quering using java sdk, there must be partition-key specified in the keyconditionexpression, which in my case won't be feasible.

Can anyone suggest me any suitable query for this problem.  Or any useful document link can also help. Thanks ...

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
