### ISSUE TITLE
Discrepancy in DynamoDB Local

### ISSUE THREAD

**Issue by b4brijesh-tataaig** [awsdocs/amazon-dynamodb-developer-guide#252]
I am not sure if this is the most appropriate place to report this but here it goes...

The documentation on page: [DynamoDB Streams and Time to Live](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/time-to-live-ttl-streams.md) mentions the `type` and `principalId` keys in camelCase which is correct, but while using DynamoDB Local during development & testing using the installable version of [DynamoDB Local Asia-Pacific Mumbai Region](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html) the keys are actually in PascalCase.

We actually faced a production issue because of this, where our assumption that a functionality working on DynamoDB Local would also seamlessly work on the actual DB costed us. This should be fixed by the concerned team at AWS, or at least should be pointed out in the [Usage Notes](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DynamoDBLocal.UsageNotes.md).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
