### ISSUE TITLE
Potentially wrong or confusing PartiQL example

### ISSUE THREAD

**Issue by pgrm** [awsdocs/amazon-dynamodb-developer-guide#259]
Hello, I do not understand why this condition does **NOT** result in a full table scan:

https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/ql-reference.select.md?plain=1#L53

```sql
SELECT * 
FROM Orders 
WHERE OrderID = 100 or pk = 200
```

is this a mistake in the example? or did I miss something?

couple lines below, there is the following example, which according to the docs results in a full table scan

```sql
SELECT * 
FROM Orders 
WHERE OrderID = 100 OR Address='some address'
```

Why exactly would `or pk` be ok, if `OR Address` is not? (I do understand why the second example does result in a full table scan, I'm just confused about the first one)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
