### ISSUE TITLE
DynamoDBLocal 1.17.0Jar missing class files

### ISSUE THREAD

**Issue by piyushknoldus** [awsdocs/amazon-dynamodb-developer-guide#267]
The below jar that is uploaded is missing all the class files

Jar: release/com/amazonaws/DynamoDBLocal/1.17.0/DynamoDBLocal-1.17.0.jar

Download Location: https://s3-us-west-2.amazonaws.com/dynamodb-local/

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
