### ISSUE TITLE
Hash/Range key nomenclature

### ISSUE THREAD

**Issue by jlh-amzn** [awsdocs/amazon-dynamodb-developer-guide#27]
There is inconsistency on how we refer to Hash/Partition and Range/Sort keys. For Java code samples, the documentation mentions Hash and Range, but the written explanation refers to Partition and Sort keys. Example: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.Methods.html

My question is; should the vocabulary be unified? If so, what is the preferred nomenclature?

**Comment by santisra** [comment]
Thanks for your feedback. I'll look into this.

**Comment by NicholasDunham** [comment]
Yes, in the documentation we use "partition key" and "sort key," but in APIs you'll see "hash key" and "range key." Unfortunately it's not something we can easily change at this point.
