### ISSUE TITLE
ClusterDaxAsyncClient example code doesn't work

### ISSUE THREAD

**Issue by dhoss** [awsdocs/amazon-dynamodb-developer-guide#271]
in the page documenting how to modify an existing project to use DAX: 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.modify-your-app.html

the following code doesn't even seem to exist in ```ClusterDaxAsyncClient```:
```ClusterDaxAsyncClient.builder()```

There is no ```builder()``` method in ```the ClusterDaxAsyncClient``` javadoc:
http://dax-sdk.s3-website-us-west-2.amazonaws.com/javadocs/hosted/com/amazon/dax/client/dynamodbv2/ClusterDaxAsyncClient.html#ClusterDaxAsyncClient-com.amazon.dax.client.dynamodbv2.ClientConfig-

The constructor in the documentation looks like this:
```public ClusterDaxAsyncClient(ClientConfig cfg)```

Am I missing something?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
