### ISSUE TITLE
How does reserved capacity interact with Infrequent Access tables?

### ISSUE THREAD

**Issue by alexwlchan** [awsdocs/amazon-dynamodb-developer-guide#273]
I've heard third-hand that reserved capacity doesn't apply to Infrequent Access tables.

Is this true? Could it be clarified in the documentation somewhere?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
