### ISSUE TITLE
Get AmazonDynamoDBException 

### ISSUE THREAD

**Issue by vivekgowdatv1992** [awsdocs/amazon-dynamodb-developer-guide#274]
Amazon.DynamoDBv2.AmazonDynamoDBException: 'Either the KeyConditions or KeyConditionExpression parameter must be specified in the request.'

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
