### ISSUE TITLE
DynamoDB local setup guide not explanatory enough for first timer

### ISSUE THREAD

**Issue by St80ene** [awsdocs/amazon-dynamodb-developer-guide#275]
The Documentation should be user friendly enough for someone installing for the first time

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
