### ISSUE TITLE
Missing `DynamoDBMapperConfig.SaveBehavior`s PUT, APPEND_SET, UPDATE_SKIP_NULL_ATTRIBUTES

### ISSUE THREAD

**Issue by texastony** [awsdocs/amazon-dynamodb-developer-guide#277]
According to the [API documentation, the Dynamo DB Mapper supports 5 Save Configs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.SaveBehavior.html).

Currently, the Developer Guide provides only 2.

https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/6160b0c9d503f99f5eb34cfd55003b62308c9b4f/doc_source/DynamoDBMapper.OptionalConfig.md?plain=1#L34-L36

Presumable the other 3 should be added as:
```
+ `APPEND_SET`--treats scalar attributes (String,Number, Binary) the as `UPDATE_SKIP_NULL_ATTRIBUTES` does.
+ `PUT` -- during a save operation, will clear and replace all attributes on save, including unmodeled ones, but fails if values do not match what is persisted on conditional writes and does not overwrite auto-generated values.
+ `UPDATE_SKIP_NULL_ATTRIBUTES` -- is similar to UPDATE, except that it ignores any null value attribute(s) and will NOT remove them from that item in DynamoDB.
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
