### ISSUE TITLE
Missing full list of possible Dax `Cluster.Status` values

### ISSUE THREAD

**Issue by DanielTemesgen** [awsdocs/amazon-dynamodb-developer-guide#279]
It's currently unclear in the docs the full list of possible Dax Cluster Status values.
I saw these two statuses (quote below) at this [link](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.cluster-management.html).
```
The cluster status changes to `modifying` when you modify the replication factor. The status changes to `available` when the modification is complete.
```
But it would be great know a full list of possible Status values, for instance like the ones shown for [Amazon Aurora DB clusters](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/accessing-monitoring.html) below (table truncated).

DB cluster status | Billed | Description
-- | -- | --
available | Billed | The DB cluster is healthy and available. When an Aurora Serverless cluster is available and paused, you're billed for storage only.
backing-up | Billed | The DB cluster is currently being backed up.
backtracking | Billed | The DB cluster is currently being backtracked. This status only applies to Aurora MySQL.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
