### ISSUE TITLE
batch delete example needed in "Running Batch Operations with PartiQL for DynamoDB"

### ISSUE THREAD

**Issue by kid1412621** [awsdocs/amazon-dynamodb-developer-guide#280]
This [doc](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.multiplestatements.batching.html) not supplies with batch delete operation. Need some clarification.
why this not work?
`DELETE FROM Music WHERE Artist=? AND begins_with(SongTitle, ? ) `
but this works.
`DELETE FROM Music WHERE Artist=? AND SongTitle= ? `

**Comment by kitsunde** [comment]
It's documented here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.delete.html

> You can only delete one item at a time. You cannot issue a single DynamoDB PartiQL statement that deletes multiple items.

You can't pass range selecting statements like `begins_with`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
