### ISSUE TITLE
Poor example for time series data guidance

### ISSUE THREAD

**Issue by rizblie** [awsdocs/amazon-dynamodb-developer-guide#290]
RE: file `doc_source/bp-time-series.md`

The example given uses the same parition key date value for every item in the table. The whole table would effectively be constrained to one partition.

Better to create a composite PK using the date and part of the timestamp (currently used as the sort key), or just use part of the timestamp as PK and then use the date in the table name (as the example seems to be using a single day period per table) e.g. partition per hour.

If data point distribution is uneven over the day, then combine above with calculated suffix sharding so that it is still possible to read all data in order.

I get that the point of this page is to illustrate the principle of a separate table per period - but the example could mislead readers into thinking that they should set the PK to the same value throughout.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
