### ISSUE TITLE
Docs missing integral point on incrementing version number in DynamoDB Version Control instructions

### ISSUE THREAD

**Issue by akirsch2** [awsdocs/amazon-dynamodb-developer-guide#292]
Missing instructions how to save, find, sort by, current version number while using AWS best practice for DynamoDB Version Control.
Due to Sort key being a String, and Strings get sorted by their UTF-8 value (not numerical).
See my [Pull Request](https://github.com/awsdocs/amazon-dynamodb-developer-guide/pull/291) on this please.
This is something basic and it's not mentioned in the docs.

@Carey-AWS @fletpatr @indrora

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
