### ISSUE TITLE
Outdated documentation for converting non standard types to DynamoDB types

### ISSUE THREAD

**Issue by protyay** [awsdocs/amazon-dynamodb-developer-guide#293]
The documentation seems to be outdated.
`DynamoDBTypeConverter` interface doesn't exist on v2 Java SDK.

This should use new class `AttributeConverter` and provide implementation.

## Links
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.ArbitraryDataMapping.html

Will start working on the fix and raise PR in the next week. Discussed this issue previously [here](https://github.com/aws/aws-sdk-java-v2/issues/3355)

Can anyone please confirm if the v2 code examples can be modified in this repository or is there a separate convention ? 

Thanks. 🙏

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
