### ISSUE TITLE
bp-partition-key-design.md uses confusing language about breaking up items collections

### ISSUE THREAD

**Issue by RossWilliams** [awsdocs/amazon-dynamodb-developer-guide#299]
In bp-partition-key-design.md
> You can also break up an item collection into segments by sort key, as long as the item collection isn't traffic that is tracked by a monotonic increase or decrease of the sort key

The language suggests that the developer can break up an item collection into segments, but I believe the intent is to say that "DynamoDB may break up an item collection into segments by sort key"

In addition, the language "isn't traffic that is tracked" is confusing as traffic tracking is not a concept for DynamoDB users. It is unclear if traffic refers to writes, reads, or both. Does this condition apply if all writes are monotonic increases, but reads are random?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
