### ISSUE TITLE
DAX not Receiving Traffic from Node.JS on EC2? No Error Messages Reported.

### ISSUE THREAD

**Issue by charlieding** [awsdocs/amazon-dynamodb-developer-guide#3]
https://stackoverflow.com/questions/49195143/aws-dax-node-js

**Comment by charlieding** [comment]
I realized that this was due to the DEMO files using ddbClient instead of daxClient. The instruction did not mention this code needed to be changed to be able to test DAX.

If you guys change the code to use the daxClient, this issue will be solved

**Comment by santisra** [comment]
We'll look into this. Thanks

**Comment by santisra** [comment]
We just updated the node.js example and this should be now fixed. Feel free to reopen if that's not the case.
