### ISSUE TITLE
DynamoDBContext needs to describe DynamoDBEntryConversion

### ISSUE THREAD

**Issue by antmeehan** [awsdocs/amazon-dynamodb-developer-guide#300]
The description of [DynamoDBContext](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DotNetDynamoDBContext.md) should include a section on the `DynamoDBEntryConversion` value. There are some major behavioural differences between the `V1` and `V2` settings (where `V1` is the default) which are not obvious.

See https://github.com/aws/aws-sdk-net/issues/1995 for where I got burnt 😄

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
