### ISSUE TITLE
Antlr4 version is too old

### ISSUE THREAD

**Issue by andrew-lazovik** [awsdocs/amazon-dynamodb-developer-guide#307]
My project is using the framework antlr4 version of 4.11.1
I want to use DynamoDbLocal, but DynamoDbLocal also uses antlr4, and it has too old version - 4.5 
Version 4.11.1 and 4.5 are unfortunately not compatible

Can the team upgrade antlr4 version in DynamoDBLocal for java?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
