### ISSUE TITLE
DynamoDBLocal clarification for Apple Silicon

### ISSUE THREAD

**Issue by dreams-and-thoughts** [awsdocs/amazon-dynamodb-developer-guide#313]
From this page:
https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DynamoDBLocal.DownloadingAndRunning.md
https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

The following note seems to indicate Apple Silicon support for Local DynamoDB:
```
Note
DynamoDB local v1.20 and greater is required for use on M1 and newer Apple processors.
```

Trying to get this working using only DynamoDBLocal fails:

```
testImplementation("com.amazonaws:DynamoDBLocal:1.22.0")
```

I have to also add this library:

```
testImplementation("io.github.ganadist.sqlite4java:libsqlite4java-osx-aarch64:1.0.392")
```

I can also use older versions of DynamoDBLocal:

```
testImplementation("com.amazonaws:DynamoDBLocal:1.13.6")
testImplementation("io.github.ganadist.sqlite4java:libsqlite4java-osx-aarch64:1.0.392")
```

A related SO question:
https://stackoverflow.com/questions/66635424/dynamodb-local-setup-on-m1-apple-silicon-mac

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
