### ISSUE TITLE
API Permissions Reference document missing "CreateBackup" and "RestoreTableFromBackup"

### ISSUE THREAD

**Issue by yaseenkadir** [awsdocs/amazon-dynamodb-developer-guide#37]
The [api-permissions-reference.md](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/c420420a59040c5b3dd44a6e59f7c9e55fc922ef/doc_source/api-permissions-reference.md) document is missing "dynamodb:CreateBackup" and "dynamodb:RestoreTableFromBackup".

These permissions have been defined in [backuprestore_IAM.md](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/c420420a59040c5b3dd44a6e59f7c9e55fc922ef/doc_source/backuprestore_IAM.md).

**Comment by santisra** [comment]
I'll add them up. Thanks!

**Comment by yaseenkadir** [comment]
Looks like it's missing a couple more

- `dynamodb:DeleteBackup`
- `dynamodb:ListBackups`

**Comment by santisra** [comment]
This is fixed. Thanks!
