### ISSUE TITLE
NoRouteException

### ISSUE THREAD

**Issue by yeshwenth** [awsdocs/amazon-dynamodb-developer-guide#39]
Hi, i am getting the below error when connecting to the DAX cluster using the python amazon-dax-client from an EC2 instance.
DaxClientError: An error occurred (NoRouteException) when calling the  operation: Failed to configure cluster endpoints .

Can someone help?

**Comment by yeshwenth** [comment]
I figured this i think,I was not initializing the client correctly. Thanks

**Comment by grolljak** [comment]
Hi, @yeshwenth, could you elaborate how you changed the client initialization? I am getting the same error aswell.
