### ISSUE TITLE
DaxClientError

### ISSUE THREAD

**Issue by atdevyesh** [awsdocs/amazon-dynamodb-developer-guide#40]
I am new to AWS and to dynamodb. I am trying to set DAX for my dynamodb clusters.
I am going through the examples given in the doc. I see some issues.

When i run with python 03-getitem-test.py i can see the execution. 
But when i run with sudo sudo python 03-getitem-test.py i see
 DaxClientError('Failed to configure cluster endpoints from {}'.format(seeds), DaxErrorCode.NoRoute).amazondax.DaxError.DaxClientError: An error occurred (NoRouteException) when calling the  operation: Failed to configure cluster endpoints.

Since this amazondax client is on the TCP level, do i need do anything to run this as root?

Can someone help me to understand whats the difference between running this as python vs sudo python in EC2 Linux?

**Comment by NicholasDunham** [comment]
Hi @atdevyesh, I'm going through the backlog of issues and wonder if you still see the same problem. The code samples have changed a lot since you posted this, but I don't want to close it if the issue still exists. Let me know if you're still having a problem!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
