### ISSUE TITLE
DynamoDB PDF docs have issues with image scaling

### ISSUE THREAD

**Issue by constb** [awsdocs/amazon-dynamodb-developer-guide#41]
They say, one pic worths a hundred words, well, there you go…

<img width="1147" alt="2018-07-30 15 50 03" src="https://user-images.githubusercontent.com/1006766/43387294-465ef464-9410-11e8-9327-70f108a73f0d.png">

**Comment by santisra** [comment]
Thanks, we will look into this.

**Comment by NicholasDunham** [comment]
I believe I've fixed all the images that weren't scaling properly. Thanks for letting us know!
