### ISSUE TITLE
bp-modeling-nosql-B inconsistent

### ISSUE THREAD

**Issue by MaunyM** [awsdocs/amazon-dynamodb-developer-guide#44]
Hello,

I think that Query conditions are not up to date with database schema.
For exemple for Access pattern 2, the PK of GSI-1 is an id not the employe name 
The employe name seems to be in the SK of GSI-1

**Comment by jacintoArias** [comment]
Either I do not understand this tutorial or as OP is saying the example is inconsistent.

To query employees by name the SK attribute must be an index constant such as `Employee_Name` in the overloaded GSI, as in the [first example](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-gsi-overloading.html)

Then the access pattern is a query on GSI1 with `PK='Employee_Name'` (the constant) and `SK=<employee_name>` the actual value.

I would really appreciate confirmation from AWS sources :)

**Comment by NicholasDunham** [comment]
@jacintoArias, you're correct. You'd search the GSI using ``Employee_name`` as the partition key and (for example) ``Murphy, John`` as the sort key. I'll reword that bullet point to make this more clear.
