### ISSUE TITLE
Access denied when downloading DynamoDbLocal

### ISSUE THREAD

**Issue by michalborek** [awsdocs/amazon-dynamodb-developer-guide#45]
We get access denied for https://s3-us-west-2.amazonaws.com/dynamodb-local/release 

If the repository location changed, documentation should be updated.

**Comment by santisra** [comment]
I'll look into this. Thanks for reporting!

**Comment by santisra** [comment]
This issue is no longer present, so closing for now. Please let us know if you encounter any errors with downloading DDB local. Thanks!
