### ISSUE TITLE
Confusing description of classes implementing interfaces

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/amazon-dynamodb-developer-guide#53]
The descriptions of DDB Java SDK [programmatic interfaces](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.SDKs.Interfaces.html) is confusing at points, because in context, it seems to suggest (wrongly) that the classes under discussion are implementing Java interfaces in the sense of the Java programming language.  Basically, the terms _implements_ and  _interface_ are keywords with specific meanings in Java, but these terms are being used very colloquially in the docs.

> The `com.amazonaws.services.dynamodbv2.document.DynamoDB` class implements the DynamoDB document interface\. 

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.SDKs.Interfaces.Document.html

> The `com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper` class implements the DynamoDB object persistence interface.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.SDKs.Interfaces.Mapper.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
