### ISSUE TITLE
Confusing sort key "varies"

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/amazon-dynamodb-developer-guide#54]
On the [Best Practices for Using Sort Keys to Organize Data](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-sort-keys.html) page, we have the Sort Key attribute described as _varies_ - but what does this mean?  The _sort key_ attribute of a [composite primary key](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey) can't vary for a table.

![VersionControl.png](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/images/VersionControl.png)

**Comment by NicholasDunham** [comment]
Hi Eden,
In this example, the partition key always contains an equipment ID, but the sort key has different kinds of information (including version control numbers), even though the type is always the same (namely ``String``). So all "varies" means here is that there's more than one kind of information in the sort key.

**Comment by edenhochbaum** [comment]
I disagree with closing, and I disagree with the interpretation you provide.

The sort key still has a name, regardless of what "kind" of information it contains.  The styling of the partition key as **Equipment_ID** in the chart rather than **(equipment id)** is indicating that "Equipment_ID" is the name of the partition key here.  For the chart to be consistent, there needs to be a similar name provided for the sort key.

Separate (but related), the whole example is disorienting.  The idea of the section is apparently to demonstrate how composite keys can be used to satisfy auditability requirements in the context of entity-level revisions.  But in the example, there are, like, actual data items in the table corresponding to actual audits.  The whole thing seems like just a [category error](https://en.wikipedia.org/wiki/Category_mistake) was made where an audit process (an evaluation of the revision history for an entity) is treated as something to be represented as data in the table.
