### ISSUE TITLE
Inconsistent terminology

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/amazon-dynamodb-developer-guide#55]
The terms _base table_ and _parent table_ seem to be used interchangeably throughout the docs describing secondary indexes.  My recommendation is that one term or the other be used, but not both.  Or if both are to be used, then it should be explained somewhere what the difference is (if indeed there is one.)

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html

**Comment by NicholasDunham** [comment]
Thanks for pointing this out! I've changed to "base table" throughout, and the change will be pushed to the public docs later today.
