### ISSUE TITLE
Incorrect permission in DAX Cluster guide

### ISSUE THREAD

**Issue by aph3rson** [awsdocs/amazon-dynamodb-developer-guide#60]
[amazon-dynamodb-developer-guide/doc_source/DAX.create-cluster.md:33](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blame/master/doc_source/DAX.create-cluster.md#L33): 
```markdown
The `iam:CreateRole`, `iam:CreatePolicy`, `iam:AttachPolicy` and `iam:PassRole` permissions are not included in the AWS\-managed policies for DynamoDB\. This is by design, because these permissions provide the possibility of privilege escalation: A user could use these permissions to create a new administrator policy, and then attach that policy to an existing role\. For this reason, you \(the administrator of your DAX cluster\) must explicitly add these permissions to your policy\. 
```

`iam:AttachPolicy` is not a valid permission (at least, anymore) - this should be `iam:AttachRolePolicy` (if congruent with [L27](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blame/master/doc_source/DAX.create-cluster.md#L27)).

I can submit a PR if need be.

**Comment by NicholasDunham** [comment]
Thanks! I've made the necessary change, and it will appear in the public documentation shortly.
